---
scene_parameters:
    system_parameters:
        volume_file_name: "../../data/cylinder/cylinder2_385.vtk"
        observation_file_name: "observations/cylinder2_385"
        observation_points_file_name: "../../data/cylinder/cyl2_385_obs1.vtk"
    general_parameters:
        gravity: "0 -9.81 0"
        total_mass: 0.2
        boundary_conditions_list:
            - condition_type: "elastic"   # options are "fixed" and "elastic"
              boxes_coordinates: "-0.005 -0.005 -0.002 0.005 0.005 0.002 -0.005  -0.005 0.298 0.005 0.005 0.302"
              spring_stiffness_values: "150 300"
    obs_generating_parameters:
        object_young_moduli: "150 300"
        save_observations: 1
    filtering_parameters:
        output_directory_prefix: "outCyl2_138_"
        output_directory_suffix: "_springs1observation"
        output_files_suffix: "test" 
        optim_params_size: 2
        filter_kind: "UKFSimCorr"   # options are "ROUKF", "UKFSimCorr", and "UKFClassic"
        use_unbiased_variance: "0"
        initial_stiffness: [100, 100]
        minimal_stiffness: [0, 0]
        maximal_stiffness: [100000, 100000]
        initial_standart_deviation: 100
        observation_noise_standart_deviation: 1e-3
        positions_standart_deviation: 1e-3
        transform_parameters: absolute
        sigma_points_topology: "Simplex"   # options are "Simplex" and "Star"
        sigma_points_scale: 1
        save_state: 1
        save_internal_data: 1
...

