---
system_parameters:
    volume_file_name: "../../data/liver/liver.msh"
    observation_file_name: "observations/liverControlPoint"
    observation_points_file_name: "../../data/liver/liverGen_obs1_variant2.vtk"

general_parameters:
    gravity: "0 0 0"
    density: 200 # total_mass: 0.2
    delta_time: 0.01
    solver_kind: "Euler"   # options are "Euler", "Newton", and "Symplectic"
    rayleigh_mass: 0.1
    rayleigh_stiffness: 0.1
    boundary_conditions_list:
        - condition_type: "elastic"   # options are "fixed" and "elastic"
          boxes_coordinates: "0.11 0.245 0.355 0.12 0.255 0.365  0.295 0.26 0.34 0.305 0.27 0.35"
          spring_stiffness_values: "150 300"

obs_generating_parameters:
    object_young_moduli: "150 300"
    save_observations: 1

filtering_parameters:
    common_directory_prefix: "outCyl2_138_controlPoint_liver_"
    output_directory_suffix: "_test"
    output_files_suffix: "test" 
    optim_params_size: 2
    filter_kind: "ROUKF"   # options are "ROUKF", "UKFSimCorr", and "UKFClassic"
    use_unbiased_variance: "0"
    initial_stiffness: [100, 100]
    minimal_stiffness: [50, 50]
    maximal_stiffness: [100000, 100000]
    initial_standart_deviation: 500
    observation_noise_standart_deviation: 1e-3
    positions_standart_deviation: 1e-3
    transform_parameters: project
    sigma_points_topology: "Simplex"   # options are "Simplex" and "Star"
    sigma_points_scale: 1
    save_state: 1
    save_internal_data: 1

precondition_parameters:
    usePCG: 1
    PCGUpdateSteps: 100

impact_parameters:
    observation_file_name: "observations/liverCPimpact"
    position: "0.14 0.16 0.39"

time_parameters:
    timer_name: 'filter_computation_statistics'
    time_statistics_file: "computationTime.txt"
    time_profiling: 1
    iterations_interval: 1
    iteration_amount: 300
...

