---
system_parameters:
    volume_file_name: "../../data/baseLiver/baseLiver.msh"
    observation_file_name: "observations/node"
    observation_points_file_name: "../../data/baseLiver/baseLiverGen_obs7_variant1.vtk"

general_parameters:
    gravity: "0 0 0"
    density: 200 # total_mass: 0.2
    delta_time: 0.01
    solver_kind: "Euler"   # options are "Euler", "Newton", and "Symplectic"
    linear_solver_kind: "CG"   # options are "CG" and "Pardiso"
    rayleigh_mass: 200.1
    rayleigh_stiffness: 0.1
    boundary_conditions_list:
        - condition_type: "fixed"   # options are "fixed" and "elastic"
          boxes_coordinates: "0.11 0.245 0.355 0.12 0.255 0.365  0.295 0.26 0.34 0.305 0.27 0.35"
          fixed_indices: "91 90 92 89 93 0 45 135 134"
          spring_stiffness_values: "150 300"

obs_generating_parameters:
    object_young_moduli: "150 300"
    save_observations: 1
    liver_young_moduli: "5000"

filtering_parameters:
    common_directory_prefix: "constForce_138_liver_"
    output_directory_suffix: "_test"
    output_files_suffix: "test" 
    optim_params_size: 1
    filter_kind: "ROUKF"   # options are "ROUKF", "UKFSimCorr", and "UKFClassic"
    use_unbiased_variance: "0"
    initial_stiffness: [1000]
    minimal_stiffness: [0.01]
    maximal_stiffness: [100000]
    initial_standart_deviation: 200
    observation_noise_standart_deviation: 1e-3
    positions_standart_deviation: 1e-3
    model_standart_deviation: 1e-5
    transform_parameters: project
    sigma_points_topology: "Simplex"   # options are "Simplex" and "Star"
    sigma_points_scale: 1
    save_state: 1
    save_internal_data: 1

impact_parameters:
    impact_type: "Periodic"
    applied_indices: "32 33 34 35 36 37"
    bounds: "0.045 -0.02 -0.02  0.055 0.02 0.02"

force_parameters:
    force_period: 200
    force_amplitude: 0.3
    force_value: [1.0, -1.0, 0.45]

...

